sequenceDiagram
    participant User
    participant RP
    participant OP
    User->>RP: OP selection
    RP-->>+User: 
    User-->>-OP: rich authentication request (+ required AA) 
    OP->>User: show login form
    User->>OP: insert credentials
    OP->>User: show AA list
    User->>OP: select at least one AA
    OP->>User: ask consent to grant SP to query AA
    User->>OP: give consent
    OP-->>+User: 
    User-->>-RP: authentication response
    RP->>OP: token request
    OP->>RP: token response (+ grant tokens)
    RP->>OP: userinfo request
    OP->>RP: userinfo response
    RP->>OP: wrong introspection request for grant token
    OP->>RP: introspection error response

